version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proj
    ports:
      - "4000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - local-mongo
    networks:
      - proj-network

  local-mongo:
    image: mongo
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proj-network

volumes:
  mongo-data:

networks:
  proj-network:
